//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.06 at 10:43:41 PM EST 
//


package com.bharat.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="COMPANYID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FINANCIAL_STATEMENT_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="COUNTRYISOCODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "companyid",
    "financialstatementdate",
    "countryisocode"
})
@XmlRootElement(name = "getStudentRequest")
public class GetStudentRequest {

    @XmlElement(name = "COMPANYID")
    protected int companyid;
    @XmlElement(name = "FINANCIAL_STATEMENT_DATE", required = true)
    protected String financialstatementdate;
    @XmlElement(name = "COUNTRYISOCODE", required = true)
    protected String countryisocode;

    /**
     * Gets the value of the companyid property.
     * 
     */
    public int getCOMPANYID() {
        return companyid;
    }

    /**
     * Sets the value of the companyid property.
     * 
     */
    public void setCOMPANYID(int value) {
        this.companyid = value;
    }

    /**
     * Gets the value of the financialstatementdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINANCIALSTATEMENTDATE() {
        return financialstatementdate;
    }

    /**
     * Sets the value of the financialstatementdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINANCIALSTATEMENTDATE(String value) {
        this.financialstatementdate = value;
    }

    /**
     * Gets the value of the countryisocode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOUNTRYISOCODE() {
        return countryisocode;
    }

    /**
     * Sets the value of the countryisocode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOUNTRYISOCODE(String value) {
        this.countryisocode = value;
    }

}
